/* GENERAL ACTIONS */

export const NOT_FOUND = 'Action type did not found'

/* END OF GENERAL ACTIONS */

/*  CART ACTIONS */

export const GET_CART = 'GET_CART'
export const SET_CART = 'SET_CART'
export const REMOVE_ITEM = 'REMOVE_ITEM'
export const INCREASE_AMOUNT = 'INCREASE_AMOUNT'
export const DECREASE_AMOUNT = 'DECREASE_AMOUNT'
export const ADD_TO_CART = 'ADD_TO_CART'
export const CLEAR_CART = 'CLEAR_CART'

/* END OF CART ACTIONS */

/*  FORM ACTIONS */

export const LOAD_FORM = 'LOAD_FORM'
export const TOGGLE_FORM = 'TOGGLE_FORM'
export const EMAIL_CHANGE = 'EMAIL_CHANGE'
export const PASSWORD_CHANGE = 'PASSWORD_CHANGE'
export const REPASSWORD_CHANGE = 'REPASSWORD_CHANGE'
export const USERNAME_CHANGE = 'USERNAME_CHANGE'

/* END OF FORM ACTIONS */

/*  USER ACTIONS */

export const LOAD_USER = 'LOAD_USER'
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const TOGGLE_ALERT = 'TOGGLE_ALERT'

/* END OF USER ACTIONS */

/*  PRODUCT ACTIONS */

export const TOGGLE_LOADING = 'TOGGLE_LOADING'
export const SET_PRODUCTS = 'SET_PRODUCTS'
export const PAGINATE_PRODUCTS = 'PAGINATE_PRODUCTS'
export const SET_UTILS = 'SET_UTILS'
export const RESET_FILTERS = 'RESET_FILTERS'
export const CHANGE_PAGE = 'CHANGE_PAGE'
export const SET_FILTERS = 'SET_FILTERS'
export const FILTER_PRODUCTS = 'FILTER_PRODUCTS'

/* END OF PRODUCT ACTIONS */
